return {
  "hfn92/gh.nvim",
  branch = "windows_support",
  dependencies = { "ldelossa/litee.nvim", config = true },
  keys = "<leader>gb",
  config = function()
    require("litee.gh").setup {
      icon_set = "nerd",
    }
    local wk = require "which-key"
    wk.add {
      { "<leader>g", group = "Git" },
      { "<leader>gb", group = "Github" },
      { "<leader>gbc", group = "Commits" },
      { "<leader>gbcc", "<cmd>GHCloseCommit<cr>", desc = "Close" },
      { "<leader>gbce", "<cmd>GHExpandCommit<cr>", desc = "Expand" },
      { "<leader>gbco", "<cmd>GHOpenToCommit<cr>", desc = "Open To" },
      { "<leader>gbcp", "<cmd>GHPopOutCommit<cr>", desc = "Pop Out" },
      { "<leader>gbcz", "<cmd>GHCollapseCommit<cr>", desc = "Collapse" },
      { "<leader>gbi", group = "Issues" },
      { "<leader>gbip", "<cmd>GHPreviewIssue<cr>", desc = "Preview" },
      { "<leader>gbl", group = "Litee" },
      { "<leader>gblt", "<cmd>LTPanel<cr>", desc = "Toggle Panel" },
      { "<leader>gbp", group = "Pull Request" },
      { "<leader>gbpc", "<cmd>GHClosePR<cr>", desc = "Close" },
      { "<leader>gbpd", "<cmd>GHPRDetails<cr>", desc = "Details" },
      { "<leader>gbpe", "<cmd>GHExpandPR<cr>", desc = "Expand" },
      { "<leader>gbpo", "<cmd>GHOpenPR<cr>", desc = "Open" },
      { "<leader>gbpp", "<cmd>GHPopOutPR<cr>", desc = "PopOut" },
      { "<leader>gbpr", "<cmd>GHRefreshPR<cr>", desc = "Refresh" },
      { "<leader>gbpt", "<cmd>GHOpenToPR<cr>", desc = "Open To" },
      { "<leader>gbpz", "<cmd>GHCollapsePR<cr>", desc = "Collapse" },
      { "<leader>gbr", group = "Review" },
      { "<leader>gbrb", "<cmd>GHStartReview<cr>", desc = "Begin" },
      { "<leader>gbrc", "<cmd>GHCloseReview<cr>", desc = "Close" },
      { "<leader>gbrd", "<cmd>GHDeleteReview<cr>", desc = "Delete" },
      { "<leader>gbre", "<cmd>GHExpandReview<cr>", desc = "Expand" },
      { "<leader>gbrs", "<cmd>GHSubmitReview<cr>", desc = "Submit" },
      { "<leader>gbrz", "<cmd>GHCollapseReview<cr>", desc = "Collapse" },
      { "<leader>gbt", group = "Threads" },
      { "<leader>gbtc", "<cmd>GHCreateThread<cr>", desc = "Create" },
      { "<leader>gbtn", "<cmd>GHNextThread<cr>", desc = "Next" },
      { "<leader>gbtt", "<cmd>GHToggleThread<cr>", desc = "Toggle" },
    }
  end,
}
